name: "DNM Check"
description: "Checks for the specified string in changed files of a pull request and posts a comment with the results"

branding:
  icon: "minus-circle"
  color: "white"

inputs:
  search_string:
    description: "The string to search for in changed files"
    required: false
    default: "DNM"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Get Changed Files
      id: get_changed_files
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files.[].path' > changed_files.txt
      shell: bash

    - name: Search for string
      id: search_custom_string
      run: |
        found_string=false
        while read file; do
          result=$(grep -n ".*${{ inputs.search_string }}.*" "$file" || true)

          while read line; do 
            if [[ -z "$line" ]]; then
              found_string=true
            fi
            line_number=$(echo "$line" | cut -d ':' -f 1)
            line_content=$(echo "$line" | cut -d ':' -f 2-)
            echo "::error file=${file},line=${line_number},title=DO NOT MERGE::${line_content}"
          done <<< "$result"

        done < changed_files.txt

        echo "Found string: $found_string"
        if [[ $found_string == true ]]; then
          exit 1
        else
          exit 0
        fi

      shell: bash
